#pack the chaincode for safe installing
docker exec cli peer chaincode package -n mycc -l node -p /opt/gopath/src/github.com/chaincode/fabcar/javascript -v 0 -s -S ccpack.out
#install the chaincode in the network
docker exec -e CORE_PEER_LOCALMSPID=Org1MSP -e CORE_PEER_ADDRESS=peer1.factory.workspace:7051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/factory.workspace/users/Admin@factory.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/factory.workspace/peers/peer1.factory.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org1MSP -e CORE_PEER_ADDRESS=peer2.factory.workspace:8051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/factory.workspace/users/Admin@factory.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/factory.workspace/peers/peer2.factory.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org2MSP -e CORE_PEER_ADDRESS=peer1.delivery.workspace:9051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/delivery.workspace/users/Admin@delivery.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/delivery.workspace/peers/peer1.delivery.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org2MSP -e CORE_PEER_ADDRESS=peer2.delivery.workspace:10051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/delivery.workspace/users/Admin@delivery.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/delivery.workspace/peers/peer2.delivery.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org3MSP -e CORE_PEER_ADDRESS=peer1.sales-point1.workspace:11051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point1.workspace/users/Admin@sales-point1.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point1.workspace/peers/peer1.sales-point1.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org3MSP -e CORE_PEER_ADDRESS=peer2.sales-point1.workspace:12051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point1.workspace/users/Admin@sales-point1.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point1.workspace/peers/peer2.sales-point1.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org4MSP -e CORE_PEER_ADDRESS=peer1.sales-point2.workspace:13051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point2.workspace/users/Admin@sales-point2.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point2.workspace/peers/peer1.sales-point2.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node
docker exec -e CORE_PEER_LOCALMSPID=Org4MSP -e CORE_PEER_ADDRESS=peer2.sales-point2.workspace:14051 -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point2.workspace/users/Admin@sales-point2.workspace/msp -e CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/sales-point2.workspace/peers/peer2.sales-point2.workspace/tls/ca.crt cli peer chaincode install ccpack.out -l node

#instatiate the chaincode in the orderer nodes
docker exec -e CORE_PEER_LOCALMSPID=Org1MSP -e CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/factory.workspace/users/Admin@factory.workspace/msp cli peer chaincode instantiate -o orderer1.workspace:7050 -C workspace -n mycc -l node -v 0 -c '{"Args":['']}' -P 'OR('\''Org1MSP.member'\'','\''Org2MSP.member'\'', '\''Org3MSP.member'\'','\''Org4MSP.member'\'')' --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/workspace/orderers/orderer1.workspace/msp/tlscacerts/tlsca.workspace-cert.pem --peerAddresses peer1.factory.workspace:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/factory.workspace/peers/peer1.factory.workspace/tls/ca.crt

#init the ledger
CORE_PEER_ADDRESS=peer1.factory.workspace:7051 docker exec cli peer chaincode invoke -C workspace -n mycc -c '{"Args":["initLedger"]}'